# Generated by Django 2.0.7 on 2018-07-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_directed', models.BooleanField()),
                ('type_of_edge', models.CharField(choices=[('derives_from', 'Derives from'), ('symbol_of', 'Symbol of'), ('compound_of', 'Compound of')], max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='dictionary.Node')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='dictionary.Node')),
            ],
        ),
    ]
